### ISSUE TITLE
LibOS/shim/test/regression: some test case failure.

### ISSUE THREAD

**Issue by zhangckid** [oscarlab/graphene#541]
I try to make regression test case got this report:
Basic Bootstrapping:
[Success] Basic Bootstrapping
[Success] One Argument Given
[Success] Five Arguments Given
[Success] 2 page child binary
[Success] Shared Object
[Success] Exit Code Propagation

Syscall Support:
[Success] Futex Wake Test
[Success] Private mmap beyond file range
[Fail   ] Private mmap beyond file range (after fork)
[Fail   ] SIGBUS test

File System Support:
[Success] Base /proc files present

Socket Support:
[Success] epoll_wait timeout
[Success] getsockopt

Large File Support:
[Fail   ] Ftruncate
[Fail   ] Large mmap

Do we need check why some test case always return failure?

**Comment by donporter** [comment]
Yes - this is a bug I just caught.  It is fixed in #533

**Comment by zhangckid** [comment]
OK~ Thanks Don.

**Comment by dimakuv** [comment]
@zhangckid Could you close the issue then?

**Comment by mkow** [comment]
@zhangckid ping. Could you verify if #533 solves this problem?

**Comment by zhangckid** [comment]
@mkow @donporter 
No, I have verified upstream codes, it looks still have issues.
I can't even compile the test/regression normally.

Basic Bootstrapping:

[Success ] Basic Bootstrapping

[Success ] One Argument Given

[Success ] Five Arguments Given

[Success ] 2 page child binary

[Success ] Shared Object

[Success ] Exit Code Propagation
 

Syscall Support:

[Success ] Futex Wake Test

[Success ] Private mmap beyond file range

[Fail ] Private mmap beyond file range (after fork)

[Fail ] SIGBUS test

Makefile:57: recipe for target 'regression' failed

make: *** [regression] Error 255

**Comment by donporter** [comment]
That is concerning, although seems unrelated to the ftruncate fix (but may indicate other issues).

Given that 533 is merged, this is the Jenkins run:

```
Basic Bootstrapping:
[92m[Success       ][0m Basic Bootstrapping
[92m[Success       ][0m One Argument Given
[92m[Success       ][0m Five Arguments Given
[92m[Success       ][0m 2 page child binary
[92m[Success       ][0m Shared Object
[92m[Success       ][0m Exit Code Propagation


Syscall Support:
[92m[Success       ][0m Futex Wake Test
[92m[Success       ][0m Private mmap beyond file range
[92m[Success       ][0m Private mmap beyond file range (after fork)
[92m[Success       ][0m SIGBUS test


Socket Support:
[92m[Success       ][0m epoll_wait timeout
[92m[Success       ][0m getsockopt


Large File Support:
[92m[Success       ][0m Ftruncate
[92m[Success       ][0m Large mmap
[Pipeline] sh
+ cd LibOS/shim/test/apps/ltp
```

Perhaps doing a clean rebuild?

**Comment by omeg** [comment]
Clean rebuild on a current master, still getting SIGBUS failure on SGX:

```
Basic Bootstrapping:
[Success       ] Basic Bootstrapping
[Success       ] One Argument Given
[Success       ] Five Arguments Given
[Success       ] 2 page child binary
[Success       ] Shared Object
[Success       ] Exit Code Propagation


Syscall Support:
[Success       ] Futex Wake Test
[Success       ] Private mmap beyond file range
[Success       ] Private mmap beyond file range (after fork)
[Fail          ] SIGBUS test
Makefile:57: recipe for target 'regression' failed
make: *** [regression] Error 255
```

**Comment by mkow** [comment]
`Large mmap` is now fixed on master. What about other cases?
AFAIR the problem is that SIGBUS doesn't work on SGX and shouldn't be run in this mode. I guess we should fix the SGX mode check, so it won't run on SGX and won't confuse people?

**Comment by dimakuv** [comment]
Why would SIGBUS test case be triggered in SGX case? There is a clear check in `30_mmap.py`:
```python
if not sgx:
    regression.add_check(name="SIGBUS test",
                         check=lambda res: "mmap test 5 passed" in res[0].out and \
                         "mmap test 8 passed" in res[0].out)
```

On my system, running `make SGX_RUN=1 regression` doesn't trigger the SIGBUS test, as it should.

**Comment by omeg** [comment]
I think it works properly on Jenkins (is skipped). It was failing for me when running manually because I didn't realize it needs `SGX_RUN=1` not `SGX=1`.

**Comment by mkow** [comment]
So, do we have any issue here left? If not, please close this issue.

**Comment by mkow** [comment]
Closing because of no response for quite some time and because the issue seems to be resolved now.
@zhangckid Don't hesitate to reopen it in case you still see the issue.
